### ISSUE TITLE
dead link / gtCommands.pdf is missing

### ISSUE THREAD

**Issue by msalle** [gridcf/gct-docs#10]
It seems the gtCommands.pdf is not being built or published, it's in the [Makefile](https://github.com/gridcf/gct-docs/blob/gh-pages/6.2/appendices/commands/Makefile),
but does not seem to be there in the release, not from [6.2](https://gridcf.org/gct-docs/6.2/appendices/commands/index.html) nor [latest](https://gridcf.org/gct-docs/latest/appendices/commands/index.html) nor in Frank's [mockup](https://fscheiner.github.io/gct-docs/latest/appendices/commands/index.html), see the `You can also download a PDF version here` link.

**Comment by fscheiner** [comment]
PDFs created from ADOC files are not included in the repo since the beginning (see https://mailman.egi.eu/pipermail/gt-eos/2018-March/000154.html). There are several other dead links at the moment pointing to not created PDFs.

****

@msalle @matyasselmeci @ellert 
What should we do about that?

**A** Remove the dead links?
**B** Also create the PDFs?

The latter will also require to check the PDF output (see post linked above).

I personally tend to A as this means less work for us and users can still create the PDFs themselves if need by.

**Comment by matyasselmeci** [comment]
Let's just remove the links. I suspect most people would prefer the HTML documentation, and I don't want to put a bunch of binary files in the repo.

**Comment by fscheiner** [comment]
+1 from me. I can take care of that and will refer to this ticket in the corresponding PR so it's closed automatically then.

**Comment by msalle** [comment]
Either is fine with me as long as there are no dead links.
Personally I like pdf's but I agree most people will probably not use them.

**Comment by fscheiner** [comment]
@msalle 
...and the PDFs can still be created in the future, I'll just remove the dead links to PDF files.
