### ISSUE TITLE
Automate building .html pages from .adoc files

### ISSUE THREAD

**Issue by matyasselmeci** [gridcf/gct-docs#4]
A CI script should automate building and deploying changes to .adoc files as HTMLs, so we don't have to remember to do it manually.

**Comment by fscheiner** [comment]
Should we then split up source files and HTML (plus "static" files like images and other documents) into different branches?

**Comment by matyasselmeci** [comment]
Yes, I think we should. For OSG documentation, `master` only contains the source files and the CI builds into a `gh-pages` branch. I'll give this to @brianhlin since he's the one that set up that system.

**Comment by fscheiner** [comment]
@brianhlin 
Any news on this?

**Comment by brianhlin** [comment]
Hi @fscheiner sorry that this fell off my radar. Is this something we still need?

**Comment by fscheiner** [comment]
> @brianhlin 
> Hi @fscheiner sorry that this fell off my radar. Is this something we still need?

Well, this was actually @matyasselmeci 's proposal. But it would be indeed useful, because whenever committers use different AsciiDoctor versions, the HTML files differ in much more than just the changes in the ADOC files they're based on. So a lot of useless stuff gets in the repo's history over time.

****

If we can can do with the "features" of Markdown alone, we could do the same as with the gridcf.org site and just host Markdown files and let Jekyll translate that to HTML on the fly. Of course we would then have to change a lot of files and I think the inclusion functionality doesn't work for Markdown - which OTOH could make things actually a little simpler.

Just recognized https://github.com/asciidoctor/jekyll-asciidoc, maybe that could provide a similar functionality with our existing ADOC files.

**Comment by matyasselmeci** [comment]
I've started working on having Travis do this using asciidoctor; you can see the changes on my gh-pages-travis branch: https://github.com/matyasselmeci/gct-docs/tree/gh-pages-travis

**Comment by fscheiner** [comment]
Fixed with #26 and https://github.com/gridcf/gct-docs/commit/c8ecc9696b0bbbab203703cf372d05766d166081, https://github.com/gridcf/gct-docs/commit/11d4eff576249f3773c0a14379cdceee5eee326a and https://github.com/gridcf/gct-docs/commit/ec20e78876f2126d968a7af63ecd43cb6a66e1d0.
